### ISSUE TITLE
rms causes bug in R notebook with psych::describe()

### ISSUE THREAD

**Issue by Deleetdk** [harrelfe/rms#100]
This is a really weird bug, but I have narrowed it down to this combination of packages.

Reprex in R notebook. There is no error in a regular interactive session.

[psych describe R notebook bug.pdf](https://github.com/harrelfe/rms/files/5932217/psych.describe.R.notebook.bug.pdf)

Key lines:

```
psych::describe(iris)
## Error in as.data.frame.default(utils::head(x, maxPrint)): cannot coerce class '"describe"' to a data.frame
```

**Comment by harrelfe** [comment]
It appears that `psych` does not respect the fact that `Hmisc::describe` "got there first".  The only solution I know is to not issue `library(rms)` or `require(rms)` before you run `psych` functions.
