### ISSUE TITLE
calibrate following aregImpute and fit.mult.impute

### ISSUE THREAD

**Issue by vahabo** [harrelfe/rms#101]
Hello,
I multiply imputed missing data with aregImpute and fitted a logistic model with fit.mult.impute. How can I use calibrate and validate. Both gives the error "Error in calibrate.default(.fit) : fit did not use x=TRUE,y=TRUE"
How can I add  x=TRUE,y=TRUE to the fit
thank you in advance

**Comment by harrelfe** [comment]
`validate` and `calibrate` do not handle the case where multiple imputation has been done.
