### ISSUE TITLE
cph fails with boolean input

### ISSUE THREAD

**Issue by gforge** [harrelfe/rms#15]
It seems that `model.matrix()` returns TRUE together with the variable name. Not sure when this happend, can't find any [note of it](https://cran.r-project.org/src/base/NEWS) but the following code used to run fine:

```R
set.seed(10)
n <- 500
ds <- data.frame(
  ftime = rexp(n),
  fstatus = sample(0:1, size = n, replace = TRUE),
  x = factor(sample(LETTERS[1:4], size = n, replace = TRUE)),
  boolean = sample(c(TRUE, FALSE), size = n, replace = TRUE),
  subsetting = factor(sample(c(TRUE, FALSE), size = n, replace = TRUE)))

library(rms)
dd <<- datadist(ds)
options(datadist="dd")

fit <- cph(Surv(ftime, fstatus == 1) ~ x + boolean, data=ds)
```

Now it throws an `Error in X[, mmcolnames, drop = FALSE] : subscript out of bounds` as the mmcolnames has the name for the boolean variable while the `X <- model.matrix(sformula, X)` returns the boolean column with the name `booleanTRUE`.

Btw - congratulations on the second edition. Great to see that it has finally arrived.

**Comment by harrelfe** [comment]
On 12/15/2015 03:03 PM, Max Gordon wrote:
>
> It seems that |model.matrix()| returns TRUE together with the variable 
> name. Not sure when this happend, can't find any note of it 
> <https://cran.r-project.org/src/base/NEWS> but the following code used 
> to run fine:
>
> set.seed(10)
> n  <-  500
> ds  <-  data.frame(
>    ftime  =  rexp(n),
>    fstatus  =  sample(0:1,size  =  n,replace  =  TRUE),
>    x  =  factor(sample(LETTERS[1:4],size  =  n,replace  =  TRUE)),
>    boolean  =  sample(c(TRUE,FALSE),size  =  n,replace  =  TRUE),
>    subsetting  =  factor(sample(c(TRUE,FALSE),size  =  n,replace  =  TRUE)))
>
> library(rms)
> dd  <<-  datadist(ds)
> options(datadist="dd")
>
> fit  <-  cph(Surv(ftime,fstatus  ==  1)~  x  +  boolean,data=ds)
>
> Now it throws an |Error in X[, mmcolnames, drop = FALSE] : subscript 
> out of bounds| as the mmcolnames has the name for the boolean variable 
> while the |X <- model.matrix(sformula, X)| returns the boolean column 
> with the name |booleanTRUE|.
>
> Btw - congratulations on the second edition. Great to see that it has 
> finally arrived.
>

Thanks Max.

I hadn't tested recent changes with a logical variable.  Will fix this 
and will make a new release of rms soon as I've made other changes too.

Frank

> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/harrelfe/rms/issues/15>.
>

-- 
------------------------------------------------------------------------
Frank E Harrell Jr 	Professor and Chairman 	School of Medicine

	Department of *Biostatistics* 	*Vanderbilt University*

**Comment by harrelfe** [comment]
This has now been fixed and I just submitted a new version (with the fix) to CRAN.
