### ISSUE TITLE
ggplot.Predict uneven legend colors on multiplot

### ISSUE THREAD

**Issue by johnwoodill** [harrelfe/rms#19]
I'd like to plot a multi-panel plot from a multivariate regression with `ggplot.Predict()` but I'm running into issues with the paneling have different colors than in the legend.  It appears the first panel has a different palette, but I'm not entirely sure why.  When plotting more than two panels, it is only the first panel which is different; all of the other panels have the same color palette, but is not identified in the legend.  The base graphics `plot()` works fine.  

There is also an error message:

> Warning messages:
> 1: `show_guide` has been deprecated. Please use `show.legend` instead. 

Which eluded me to think it was version problem with ggplot, but after downgrading ggplot `Hmisc` would not load because it needs `ggplot 2.0`.  Do you think this error could be causing the problem? 

Here is an example:
```
dd = data.frame(x1 = 2 + (runif(200) * 6), x12 = 100 + (runif(200) * 6))
dd$y1 = rep(c(1.2, 1.4), each = 100) * dd$x1 + (runif(200) / 5)

library(rms)
ddist <- datadist(dd)
options("datadist" = "ddist")

g <- ols(y1 ~ x1 + x12, data = dd, x = TRUE, y = TRUE)
a <- Predict(g)

h <- ols(y1 ~ I(x1^2) + I(x12^2), data = dd, x = TRUE, y = TRUE)
b <- Predict(h)

p <- rbind(a,b)
ggplot(p, group = ".set.") 
```

[ggplot Plot](http://i.stack.imgur.com/BzNOC.png)

System Info:

R version 3.2.3 (2015-12-10)
Platform: x86_64-redhat-linux-gnu (64-bit)
Running under: Fedora 22 (Twenty Two)

other attached packages:
[1] rms_4.4-1       SparseM_1.7     Hmisc_3.17-1    ggplot2_2.0.0   Formula_1.2-1   survival_2.38-3 lattice_0.20-33

**Comment by harrelfe** [comment]
I fixed slow_guide but the color problem persists.  I typed ggplot(p, group='.set.') to show the ggplot2 expression that ggplot.Predict is using:

`[1] "ggplot(zz, aes(x=.xx., y=.yhat, color=.cond)) + geom_line() + coord_cartesian(ylim=c(2, 12)) + labs(x=expression(x1), y=\"y1\") + theme(plot.margin = grid::unit(rep(0, 4), 'cm')) + colFun(name=expression(Set)) + theme(legend.position='top') + tanova(w, xa, ya, c(2, 8), c(2, 12), flip=FALSE) + geom_ribbon(aes(ymin=lower, ymax=upper), alpha=0.2, linetype=0, fill=I('black'),show.legend=FALSE)"
`

If you can see what's wrong with my ggplot2 calls I can fix.

**Comment by anlepoly** [comment]
I'm also using the ggplot.Predict function. I was wondering whether I can change the background theme as white. It seems that I cannot directly use "+ theme_bw()".

**Comment by harrelfe** [comment]
Try using the `addlayer` argument

------------------------------
Frank E Harrell Jr      Professor and Chairman      School of Medicine

Department of *Biostatistics*      *Vanderbilt University*

**Comment by anlepoly** [comment]
Hi Prof. Harrell, it works well, thank you so much!
