### ISSUE TITLE
Error in !se.fit : invalid argument type

### ISSUE THREAD

**Issue by piotrp88** [harrelfe/rms#21]
There's an error in cph().
Passing `surv="summary"` to `cph()` as suggested by the official documentation returns the following error:
`Error in !se.fit : invalid argument type`
More generally, it seems that setting `surv` to a non boolean value generates the error. Probably this line of code needs to be corrected:
https://github.com/harrelfe/rms/blob/master/R/cph.s#L328

May be the docs are wrong about setting `surv="summary"`?

**Comment by harrelfe** [comment]
Fixed for next release to CRAN (soon).  Thanks.

**Comment by piotrp88** [comment]
Thank you very much! I'm looking for the next release :+1:
