### ISSUE TITLE
Size of cph() return value is much bigger compared to coxph()

### ISSUE THREAD

**Issue by piotrp88** [harrelfe/rms#22]
Linear predictors and residuals returned by `cph()` have a bigger size compared to the values returned by `coxph()` from the `survival` package.
Casting them to double solves the issue and brings them to the same size as `coxph()`. Some pseudo-code:
`as.double(cph(...)$linear.predictors)`
`as.double(cph(...)$residuals)`

This is an issue for large models. For example, using the same data (~2.7 milions of rows), same formula and same methods, `coxph()` returns an object of ~186Mb size while `cph()` returns an object of ~331Mb. Anyone can try with his own data and compare the twos.

**Comment by harrelfe** [comment]
Let me know the attributes of those two vector that you think should be dropped.

**Comment by piotrp88** [comment]
What do you mean exactly? I've compared `linear.predictors` from `coxph()` and `cph()` (say `vector1` and `vector2` respectively) and they seem to have exactly the same numeric values except from the fact that `vector2` has names (or labels).
Probably typecasting to `double` via `as.double(vector2)` forces R to drop the vector names. By doing this, you halve the vector size. I really don't know if names are used by other `rsm` functions but for a simple model output they can be dropped.
Obviously, `residuals` acts the same as `linear.predictors`.


I have a suggestion. In `cph()` you have defined the following parameters: `x`, `y`, `model` and `se.fit` which are set to `FALSE` by default. It will be nice to specify if `cph()` should return also `linear.predictors` and `residuals` by specifing `linear.predictors=F` and `residuals=F`. This helps to further reduce `cph()` return value size.

**Comment by harrelfe** [comment]
I think that's a good way to go.  I'll work on that.  I hesitate to drop the names attribute because that is handy when there are NAs.

**Comment by piotrp88** [comment]
It could be an option, like `linear.predictors.names=T` and `residuals.names=T`. 

If you want to make a more generic option you could also introduce the `vector.names=T` option which applies for all returned vectors.

I work with survival datasets that has 100 to 300 milions of rows and the output returned by `coxph()` has a size of tens of GigaBytes while `cph()` doubles it, as stated before. Introducing all these options should significantly reduce computational times and swap usage.

Thank you for your work and dedition
 Pietro

**Comment by harrelfe** [comment]
Just committed these changes: added new arguments linear.predictors, residuals, nonames.  Set nonames to TRUE to omit names attribute from 4 objects.

**Comment by piotrp88** [comment]
Thank you! Can't wait for the next release to test the new changes :+1:
