### ISSUE TITLE
lrm() error: Error in X[, mmcolnames, drop = FALSE] : subscript out of bounds

### ISSUE THREAD

**Issue by dalewsteele** [harrelfe/rms#25]
I've been getting an error using lrm().  The equivalent glm() model runs without error.  

Reproducible example below:

Small subset of my data:
```
tbi_ss <- structure(list(PosIntFinal = structure(c(1L, 1L, 2L, 1L, 1L, 
1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L
), .Label = c("No", "Yes"), class = "factor"), GCSTotal = c(15, 
15, 14, 15, 15, 15, 15, 15, 15, 14, 15, 15, 15, 15, 15, 15, 15, 
15, 15, 15, 15)), .Names = c("PosIntFinal", "GCSTotal"), row.names = c(NA, 
-21L), class = c("tbl_df", "tbl", "data.frame"))
```

`m_lrm <- lrm(PosIntFinal ~ as.factor(GCSTotal), data=tbi_ss)`

produces the error:
`Error in X[, mmcolnames, drop = FALSE] : subscript out of bounds`

`m_glm <- glm(PosIntFinal ~ as.factor(GCSTotal), family="binomial", data=tbi_ss)`

fits the model without complaint.

**Comment by harrelfe** [comment]
as.factor should never have worked with rms.  It only worked by accident before.  Make it a factor in the data table or data frame and put the plain variable name in the model.  If you want to revert to a numeric form in a later model try the scored function.
