### ISSUE TITLE
survplot with npsurv: n.risk at time=0 is same across strata

### ISSUE THREAD

**Issue by tonigi** [harrelfe/rms#27]
I am not sure if this is the intended behaviour, but when using survplot with an npsurv object and n.risk=T, the number at risk for all strata but the first appears to be incorrect at t=0. E.g.

```
example(survplot)    # reuse objects of the example 
survplot(npsurv(S~sex),n.risk=T)
```

**Comment by harrelfe** [comment]
See an existing note about this.  This was a survival package bug, and a
recent version of survival from CRAN fixes the problem.

------------------------------
Frank E Harrell Jr      Professor and Chairman      School of Medicine

Department of *Biostatistics*      *Vanderbilt University*

**Comment by tonigi** [comment]
Thanks!
