### ISSUE TITLE
predict() results incorrect when using categorical predictors with ordered levels

### ISSUE THREAD

**Issue by castor273** [harrelfe/rms#32]
Dear Prof. Harrell,

Thank you for the useful rms package. I was fortunate to attend your course a few years ago.

I would like to bring to our attention an issue (and hopefully a fix) with the predict() method for ols(). When an ordered factor is defined and used as a predictor, the predict() method with newdata won't give correct results. The self-contained example below illustrates the issue.

> library(rms)
> df <- data.frame(y=rnorm(21), day=weekdays(Sys.Date()-(1:21), abbr=T))
> df$day.ordered <- with(df, factor(as.character(day), levels=c("Sun","Mon","Tue","Wed","Thu","Fri","Sat"), ordered=T))
> options(contrasts=c("contr.treatment", "contr.treatment"))
> fit1 <- ols(y~day, data=df)
> fit2 <- ols(y~day.ordered, data=df)
> df.char <- df; df.char$day.ordered <- as.character(df.char$day.ordered)
> cbind(orig=predict(fit1), orig.newdata=predict(fit1,newdata=df), ordered=predict(fit2), ordered.newdata=predict(fit2,newdata=df), ordered.workaround=predict(fit2,newdata=df.char))

Sample output:
         orig orig.newdata    ordered ordered.newdata ordered.workaround
1  -0.9806541   -0.9806541 -0.9806541      -1.7049262         -0.9806541
2   0.8522859    0.8522859  0.8522859      -1.7049439          0.8522859
3  -0.9279295   -0.9279295 -0.9279295      -1.8552874         -0.9279295
4  -0.7078337   -0.7078337 -0.7078337       0.5226366         -0.7078337
5   0.3559332    0.3559332  0.3559332      -1.5590623          0.3559332
[truncated]

You will note that the column "ordered.newdata" shows different results than the other columns. Redefining "day.ordered" as character serves as a workaround. Neither lm() or glm() has this issue.

I dug further into the predict() methods. I noted that predict.lm() defines an "xlev" argument when calling model.frame():

`
m <- model.frame(Terms, newdata, na.action = na.action, xlev = object$xlevels)
`

I've looked into the predictrms() function defined in github:
https://github.com/harrelfe/rms/blob/master/R/predictrms.s
At line 250, we see that the model.frame() is called without "xlev" argument

`
X <- model.frame(Terms, newdata, na.action=na.action, ...)
`
I would suggest replacing that line with the following:

`
X <- model.frame(Terms, newdata, na.action=na.action, xlev = fit$xlevels, ...)
`
Hopefully, this would fix the issue.

Best regards,
Jerome Asselin

> version
               _
platform       x86_64-redhat-linux-gnu
arch           x86_64
os             linux-gnu
system         x86_64, linux-gnu
status
major          3
minor          3.0
year           2016
month          05
day            03
svn rev        70573
language       R
version.string R version 3.3.0 (2016-05-03)
nickname       Supposedly Educational
> packageVersion("rms")
[1] ‘4.5.0’

**Comment by harrelfe** [comment]
Thanks for the report and the good test.  The problem was in predictrms in this line:

```
  oldopts <- options(contrasts=c(factor="contr.treatment",
                       ordered="contr.treatment"),   # was "contr.poly"
                     Design.attr=at)

```
This will be fixed in the upcoming release.

**Comment by castor273** [comment]
Thank you Prof. Harrell for looking into this.
With best regards,
Jerome
