### ISSUE TITLE
declaring a main effect after an interaction triggers an error

### ISSUE THREAD

**Issue by castor273** [harrelfe/rms#36]
Dear Prof Harrell,

When using %ia% in a model formula, I've noticed an error is triggered simply by declaring a main effect after the interaction. Here is a reproducible example.

```
library(rms)
df <- data.frame(y=rnorm(21), x1=rnorm(21), x2=rnorm(21))
options(contrasts=c("contr.treatment", "contr.treatment"))
fit1 <- ols(y~rcs(x1)+rcs(x2)+rcs(x1)%ia%rcs(x2),data=df)
fit2 <- ols(y~rcs(x1)+rcs(x1)%ia%rcs(x2)+rcs(x2),data=df)
```

The final lines issues an error,
> Error in Design(X) :
>   x1 x2 cannot be used in %ia% since not listed as main effect
I'm not sure if this behavior is intended. The workaround is to reorder the formula with the main effects **before** the interaction. I would expect fit1 and fit2 to return equivalent model objects, even if the terms aren't necessarily ordered the same way.

Best regards,
Jerome Asselin

> version
               _
platform       x86_64-redhat-linux-gnu
arch           x86_64
os             linux-gnu
system         x86_64, linux-gnu
status
major          3
minor          3.1
year           2016
month          06
day            21
svn rev        70800
language       R
version.string R version 3.3.1 (2016-06-21)
nickname       Bug in Your Hair
> packageVersion('rms')
[1] ‘5.0.0’

**Comment by harrelfe** [comment]
You are right the ordering is important.  If a second persons requests this I'll work on it.
