### ISSUE TITLE
Documentation of R2 for Cox PH

### ISSUE THREAD

**Issue by davidaknowles** [harrelfe/rms#37]
Apologies if this is the wrong place to put this. 

The documentation for the `cph` function does not specify what `R2` is returned, and indeed the value returned disagrees with that from `survival::coxph`. I think both are using the Cox & Snell generalized R-squared but `cph` is reporting R^2/R^2_max whereas coxph reports R^2 (and separately R^2_max). This took some amount of googling to figure out so it would be nice if was in the docs!

**Comment by harrelfe** [comment]
Good catch.  I added a sentence in cph.Rd for the next release.
