### ISSUE TITLE
Using get() for independent variable in lrm causes subscript out of bounds error

### ISSUE THREAD

**Issue by michelow** [harrelfe/rms#39]
RStudio Version 1.0.136, R 3.3.2 on Windows 8.1. Package rms 5.1-0

I am trying to do bivariate comparisons by running lrm against a large set of 21 outcome (y) and 6 predictor (x) variables using a programmed loop. The code below for lrm fails with "**Error in X[, mmcolnames, drop = FALSE] : subscript out of bounds**". If I change the call to use glm and alter the other expected parameters accordingly then the call works. It seems that the use of get() in the predictor position is causing some unhandled situation in lrm.

I'd tried to essentially achieve the following (removing all the looping mechanics):
```
vdrug <- "Alcohol"
vpred <- "Sex"
m0 <- lrm(get(vdrug) ~ get(vpred), data = w13drug_dt)
```
Interestingly, the problem is not with _any_ use of get() as the following code with get() in the y position works just fine:
```
vdrug <- "Alcohol"
m0 <- lrm(get(vdrug) ~ Sex, data = w13drug_dt)
```
And the idea of using get() in both y and x positions also works with glm; e.g.,
```
vdrug <- "Alcohol"
vpred <- "Sex"
m0 <- glm(get(vdrug) ~ get(vpred), data = w13drug_dt, family=binomial(link=logit))
```

However, the following code fails with the above-mentioned error message:
```
vpred <- "Sex"
m0 <- lrm(Alcohol ~ get(vpred), data = w13drug_dt)
```

In case it is relevant, I already had run datadist for the predictor (x) variables. The code calling lrm also works perfectly if the variable names are hardcoded; i.e., 

`m0 <- lrm(Alcohol ~ Sex, data = w13drug_dt)`

In case it was an interaction with just get(), I also tried:
```
vpred <- quote(Sex)
m0 <- lrm(Alcohol ~ eval(vpred), data = w13drug_dt)
```
but this causes the same subscript error. However, as with get(), the following code works:
```
vdrug <- quote(Alcohol)
m0 <- lrm(eval(vdrug) ~ Sex, data = w13drug_dt)
```

For the input data.frame/data.table, selected output from str(w13drug_dt) is:
> str(w13drug_dt)
Classes ‘data.table’ and 'data.frame':	172 obs. of  42 variables:
 $ Qnum           : chr  "A-07-001" "A-07-002" "A-07-003" "A-07-004" ...
 $ Alcohol        : int  0 1 1 0 0 0 0 1 0 0 ...
(snip)
 $ Sex            : Factor w/ 2 levels "Female","Male": 2 2 2 1 2 2 1 2 1 2 ...
>

**Comment by michelow** [comment]
On rereading the other thread about the same error, I tried changing the predictor variable from a factor to a simple integer and the previously failing code worked. Thus a more refined description of the error case would be when the independent variable is a factor then the get() causes the error in the call to lrm.

To be noted, get(vpred) works in glm regardless of whether vpred is a factor or integer, and it works in lrm if vpred is a factor but the variable name is hard-coded in the call to lrm instead of inserted via get().

**Comment by michelow** [comment]
Minimal code to reproduce the error:
```
library(rms)
alcohol <- c(0, 1, 1, 0, 0, 0, 0, 1, 0, 0)
sex <- c(2, 2, 2, 1, 2, 2, 1, 2, 1, 2)
sex <- as.factor(sex)
vpred <- "sex"
lrm(alcohol ~ get(vpred))

```
To make the error go away:
```
sex <- as.integer(sex)
lrm(alcohol ~ get(vpred))

```

**Comment by harrelfe** [comment]
This is not really good R practice for modeling, and I don't allow get in a model formula in rms.

**Comment by michelow** [comment]
Am assuming you mean the "not good practice" refers to potential multiple comparison related issues rather than to using R programming to handle one's analyses programmatically. The multiple comparison issue was being addressed. Thanks anyways, good to know the limits of the contexts in which lrm can be used.
Kind regards, and thanks again for the work on this useful package.

**Comment by harrelfe** [comment]
No I was referring to this practice from an R programming standpoint.  I don't want to use a formula that uses a function call that is not for a data transform.

**Comment by michelow** [comment]
Thanks for the clarification. That makes sense. I was using get() more as a convenience method for not committing to the vector names in advance and there are indeed other ways to achieve the same goal that can keep the regression function call "purer" as you've designed it. Can definitely see the potential risks avoided by precluding get. Pointer on good practice much appreciated :)
