### ISSUE TITLE
The half (1/2) unicode sign is not properly printed in survplotp legend

### ISSUE THREAD

**Issue by lianos** [harrelfe/rms#48]
Seems like a relatively recent issue, but when we render `survplotp`, instead of the legend for the grey middle band being labeled as "Difference &#189; 0.95 CL", we rather get the unicode sequence (not the symbol) printed, like so "Difference \&#189;  0.95 CL"

I guess some escaping rules somewhere (maybe in plotly?) changed.

Here's an example taken from the code in the ?suvrplot help page that reproduces the issue:

```r
library(rms)
n <- 1000
set.seed(731)
age <- 50 + 12*rnorm(n)
label(age) <- "Age"
sex <- factor(sample(c('male','female'), n, TRUE))
cens <- 15*runif(n)
h <- .02*exp(.04*(age-50)+.8*(sex=='female'))
dt <- -log(runif(n))/h
label(dt) <- 'Follow-up Time'
e <- ifelse(dt <= cens,1,0)
dt <- pmin(dt, cens)
units(dt) <- "Year"

S <- Surv(dt,e)
f <- npsurv(S ~ sex)
survplotp(f)
```

The relevant bits from session_info() are likely:

```
Session info ----------------------------------------------------------------
 setting  value
 version  R version 3.4.1 (2017-06-30)
 system   x86_64, darwin15.6.0
 ui       X11
 language (EN)
 collate  en_US.UTF-8
 tz       US/Pacific
 date     2017-09-06

Packages --------------------------------------------------------------------
 Hmisc        * 4.0-3      2017-05-02 CRAN (R 3.4.0)
 plotly         4.7.1      2017-07-29 CRAN (R 3.4.1)
 rms          * 5.1-1      2017-05-03 CRAN (R 3.4.0)
 shiny          1.0.5      2017-08-23 CRAN (R 3.4.1)
```

**Comment by lianos** [comment]
As an addendum: I guess a similar issue manifests itself on the x-axis label for the same plot, where it now reads "Follow-up Time\&#8195; Years"

**Comment by harrelfe** [comment]
Looks like `plotly` or `RStudio` changed and now they want me to use unicode instead of HTML &nnn;  I added more unicode-using code in survplotp and need to find a way to make this a general option.  More to follow.

**Comment by harrelfe** [comment]
I updated `Hmisc` for the next release to produce unicode by default.  This can be overridden by specifying `options(htmlSpecialType='&')`
