### ISSUE TITLE
lrm error with variable names

### ISSUE THREAD

**Issue by thaoz** [harrelfe/rms#55]
I have encountered a minor bug with lrm function. lrm could not fit a model with 2 variables named "X2" and "X21" in which the first one is binary with 2 levels 0 and 1, and the second one is continuous. The error message is "singular information matrix in lrm.fit". Problem is solved if I change the name of variable X2 to something else for example D2.  I do not have the same problem with glm function. 

I understand that this issue only happens in simulation study when people name their variable in a convenient way so it is kind of trivial, but I report it anyway.

**Comment by harrelfe** [comment]
I tried to reproduce this problem but could not, using the code below.

```
require(rms)
set.seed(1)
n <- 100
X2 <- c(rep(0, n/2), rep(1, n/2))
X21 <- runif(n)
y <- sample(0:1, n, TRUE)
f <- lrm(y ~ X2 + X21)

```

**Comment by thaoz** [comment]
If X2 is a factor, then the problem occurs.

**Comment by thaoz** [comment]
`require(rms)
set.seed(1)
n <- 100
X2 <- c(rep(0, n/2), rep(1, n/2))
X2 <- as.factor(X2)
X21 <- runif(n)
y <- sample(0:1, n, TRUE)
f <- lrm(y ~ X2 + X21)`

See the code

**Comment by harrelfe** [comment]
I found this problem is inherent to R:
