### ISSUE TITLE
Calibration not working for ols

### ISSUE THREAD

**Issue by tamas-ferenci** [harrelfe/rms#61]
This example (taken from the help file):

    set.seed(1)
    x1 <- runif(200)
    x2 <- sample(0:3, 200, TRUE)
    distance <- (x1 + x2/3 + rnorm(200))^2
    d <- datadist(x1,x2)
    options(datadist="d") 
    f <- ols(sqrt(distance) ~ rcs(x1,4) + scored(x2), x=TRUE, y=TRUE)
    calibrate(f)

results in `Error in !fail : invalid argument type`. (But `validate(f)` works fine.)

**Comment by harrelfe** [comment]
Sorry about that.  Fix committed to Github and will be in next release to CRAN.

**Comment by tamas-ferenci** [comment]
I checked it on my original problem, and it works, thank you!
