### ISSUE TITLE
Offset doesn't work in orm with cloglog link

### ISSUE THREAD

**Issue by tamas-ferenci** [harrelfe/rms#62]
Consider the following example:

    set.seed(1)
    n <- 100
    SimData <- data.frame( x1 = sample(c(-1,0,1), n, TRUE),
                x2 = sample(c(-1,0,1), n, TRUE),
                exposure = rlnorm(100) )
    SimData$y <- round(runif(n), 2)
    dd <- datadist(SimData)
    options(datadist="dd")
    g <- orm(y ~ x1 + x2 + offset( log( exposure ) ), family = binomial( link = "cloglog") )

I think the problem is with `orm.fit`: it seems to me that the inverse of cloglog is defined in the `families`, but when `sfam` and `csfam` is calculated, this is lost.

**Comment by harrelfe** [comment]
Finally got this fixed.  Note that in your `orm` call you need `data=` and `family='cloglog'`
