### ISSUE TITLE
[cph] Error in `[.default`(y, , 3) : subscript out of bounds

### ISSUE THREAD

**Issue by huynguyen250896** [harrelfe/rms#82]
Dear Prof. Harrelfe, 

I'm trying to construct nomogram with my cancer data. This is a summary of my data:

`    str(train)`

> 'data.frame':	1323 obs. of  25 variables:
>  
>   $ LYMPH_NODES_EXAMINED_POSITIVE: Factor w/ 3 levels
>  "<=3","<=9",">10": 3 NA 1 2 NA 1 NA 1 3 1 ...
>  
>   $ CELLULARITY                  : Factor w/ 3 levels
>  "High","Low","Moderate": NA 1 3 1 3 3 1 3 NA 1 ...
>  
>  $ MENOPAUSAL_STATE             : Factor w/ 2 levels "Post","Pre": 1 2
>  2 1 1 1 1 1 NA 2 ...
>  
>   $ ER_STATUS                    : Factor w/ 2 levels
>  "Negative","Positive": 2 2 2 2 2 2 1 2 2 1 ...
>  
>  $ OS_MONTHS                    : num  718 425 822 186 16 816 77 514 NA
>  821 ...
>  
>  $ OS_STATUS                    : Factor w/ 2 levels
>  "DECEASED","LIVING": 2 2 2 1 1 2 1 1 NA 2 ...
>  
>  $ LATERALITY                   : Factor w/ 2 levels "Left","Right": 2
>  2 2 2 1 2 1 1 NA 2 ...
> ...
>

and this is my code:

 

```
    attach(train);d <- datadist(CELLULARITY, MENOPAUSAL_STATE, ER_STATUS,
     LATERALITY, LYMPH_NODES_EXAMINED_POSITIVE)                   
     
     options(datadist = 'd')
     
     train$CELLULARITY <- train$CELLULARITY %>% factor()

     train$MENOPAUSAL_STATE <- train$MENOPAUSAL_STATE %>% factor()

     train$ER_STATUS <- train$ER_STATUS %>% factor()

     train$LATERALITY <- train$LATERALITY %>% factor() 

     train$LYMPH_NODES_EXAMINED_POSITIVE <- train$LYMPH_NODES_EXAMINED_POSITIVE %>% factor() 
     
     train$OS_MONTHS <- train$OS_MONTHS %>% as.numeric()
     
     mod.cox <- cph(formula(Surv(OS_MONTHS, OS_STATUS) ~ CELLULARITY + MENOPAUSAL_STATE + ER_STATUS + LATERALITY +LYMPH_NODES_EXAMINED_POSITIVE),
                        data=train, x= TRUE, y= TRUE, surv = TRUE)

```
Right now, I got the error:

> Error in `[.default`(y, , 3) : subscript out of bounds

I did some researches and found [this previous issue](https://github.com/harrelfe/rms/issues/31) and [this](https://github.com/harrelfe/rms/issues/25) related, which solved by you. But, It seems not working to me.

Any helps would be appreciated

**Comment by huynguyen250896** [comment]
This is the example data to reproduce the error:
https://drive.google.com/open?id=1Bi9nfg34eByc5H1Bmmq43dz6O8lEaj5O

**Comment by huynguyen250896** [comment]
It is my fault. The error is solved.

**Comment by cocococozou** [comment]
> It is my fault. The error is solved.

Hello Quang-Huy:

I ran into the same problem as you and got the error:
Error in [.default(y, , 3) : subscript out of bounds

Could you briefly explain how you solve it? Many thanks!

Best,
Coco

**Comment by huynguyen250896** [comment]
> > It is my fault. The error is solved.
> 
> Hello Quang-Huy:
> 
> I ran into the same problem as you and got the error:
> Error in [.default(y, , 3) : subscript out of bounds
> 
> Could you briefly explain how you solve it? Many thanks!
> 
> Best,
> Coco

Hello @cocococozou ,

At that time, I have realized that the error was not derived from the 'cph' function. Instead, It actually stemed from my fault that I missed a crucial step in preprocessing steps before. Unfortunately, I do not remember what exactly I missed. Can you list what variables of your interest inputted into the model?; i.e., clinical features such as AGE, tumor stages,...,

Best,

Quang-Huy Nguyen

**Comment by cocococozou** [comment]
> > > It is my fault. The error is solved.
> > 
> > 
> > Hello Quang-Huy:
> > I ran into the same problem as you and got the error:
> > Error in [.default(y, , 3) : subscript out of bounds
> > Could you briefly explain how you solve it? Many thanks!
> > Best,
> > Coco
> 
> Hello @cocococozou ,
> 
> At that time, I have realized that the error was not derived from the 'cph' function. Instead, It actually stemed from my fault that I missed a crucial step in preprocessing steps before. Unfortunately, I do not remember what exactly I missed. Can you list what variables of your interest inputted into the model?; i.e., clinical features such as AGE, tumor stages,...,
> 
> Best,
> 
> Quang-Huy Nguyen

Hi Quang-Huy:

Thank you for replying me. Attached is my code. You can find my covariants (ageaqt, Q1BMI, marital_status) and my result (event). And also the same error here. 

![IMG_8809](https://user-images.githubusercontent.com/20150135/93671611-5d7e5e80-fa72-11ea-9ca6-0f95f648235f.JPG)

**Comment by huynguyen250896** [comment]
Hey @cocococozou ,

Maybe I've just remembered what reason do the error appear already. The two variables 'ageatq' and 'Q1BMI' are continuous. You should make them categorical. For my case, my variable 'age' existed as a continuous variable at that time. I had to separate it into categories: 10, 20,...,100 and it worked. In the meanwhile, I would recommend you use the base R package ''cut' to do that.

Please inform me if it works.

Best,

Quang-Huy Nguyen

**Comment by cocococozou** [comment]
> Hey @cocococozou ,
> 
> Maybe I've just remembered what reason do the error appear already. The two variables 'ageatq' and 'Q1BMI' are continuous. You should make them categorical. For my case, my variable 'age' existed as a continuous variable at that time. I had to separate it into categories: 10, 20,...,100 and it worked. In the meanwhile, I will highly recommend you use the base R package ''cut' to do that.
> 
> Please inform me if it works.
> 
> Best,
> 
> Quang-Huy Nguyen

Hello @huynguyen250896 : 
Thanks I found the problem: it is because the "event" was in factor but instead it should be integer (which is kind of weird... 
Thank you for your help!

**Comment by huynguyen250896** [comment]
Hello @cocococozou ,

I am very glad to hear that. Hey, you've accidentally motivated me to refocus on this field.  Can I have your any other social media (e.g., Skype, Facebook, ...) that is more interactive over here. I would like to discuss more many downstream steps (after finishing drawing the nomogram) because I've been wanting to replicate results from some previous papers related to this using public data to learn additionally.

Best,

Quang-Huy Nguyen

**Comment by cocococozou** [comment]
> Hello @cocococozou ,
> 
> I am very glad to hear that. Hey, you've accidentally motivated me to refocus on this field. Can I have your any other social media (e.g., Skype, Facebook, ...) that is more interactive over here. I would like to discuss more many downstream steps (after finishing drawing the nomogram) because I've been wanting to replicate results from some previous papers related to this using public data to learn additionally.
> 
> Best,
> 
> Quang-Huy Nguyen

Happy to! I just sent you an invite through Linkedin and let me know if you want discuss more
