### ISSUE TITLE
cph 

### ISSUE THREAD

**Issue by gerjonhannink** [harrelfe/rms#92]
Hi Frank,

I just updated to rms 6.0-1, tried to run an intercept only model using `cph`:

`library(rms)`
`cph(Surv(time, status == 2) ~ 1, data = lung)`

and got the following error message:
`Error in cph(Surv(time, status == 2) ~ 1, data = lung) : object 'n' not found`

rms 6.0-0 works fine. Any ideas?

Many thanks!
Gerjon

```
R version 4.0.2 (2020-06-22)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS High Sierra 10.13.6

locale:
[1] C

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] rms_6.0-1       SparseM_1.78    Hmisc_4.4-1     ggplot2_3.3.2  
[5] Formula_1.2-3   survival_3.1-12 lattice_0.20-41
```

**Comment by harrelfe** [comment]
`rms` doesn't support intercept-only models.
