### ISSUE TITLE
broom 0.7.0 deprecates summary.lm() which removes support for rms models

### ISSUE THREAD

**Issue by Deleetdk** [harrelfe/rms#93]
**broom** package [was recently updated to 0.7.0 from 0.5.X](https://cran.r-project.org/web/packages/broom/news/news.html). This unfortunately breaks support for **rms** model functions:

> We are moving away from supporting `summary.*()` objects. In particular, we have removed `tidy.summary.lm()` as part of a major overhaul of internals. Instead of calling `tidy()` on summary-like objects, please call `tidy()` directly on model objects moving forward.

There is as yet no direct support for **rms** object, and now the only workaround has been removed, as far as I know, so one is now back to manually extracting the desired model information. [This StackOverflow question](https://stackoverflow.com/questions/47724189/extract-all-model-statistics-from-rms-fits) provides an example where this hack was used. 

It would be best if there was proper **tidy** support, and secondly, of course best if **rms** functions provided proper numerical output in the returned objects instead of calculating these in hard-to-find parts of `print`/`plot` calls. [A related case](https://stats.stackexchange.com/a/155248/78398) of this general issue is collecting the regression variable importance metrics, which are residing into a `plot` call to an `anova` wrapper that one has to call multiple times to get the desired data (these being the predictors' chisqminusdf, chisq, aic, P, partial R2, remaining R2, proportion R2, proportion chisq, [per the `anova.rms` docs](https://www.rdocumentation.org/packages/rms/versions/6.0-1/topics/anova.rms)).

Also posted this at [the **broom** repo related bug report](https://github.com/tidymodels/broom/issues/30).

**Comment by Deleetdk** [comment]
https://cran.r-project.org/web/packages/broom/news/news.html

> broom 0.7.3
> 
> In broom 0.7.0, we introduced an error for model objects that subclassed lm and relied on tidy.lm(), or similarly for tidy.glm(). Tidiers for these objects were supported unintentionally, and we worried that tidiers for these objects would silently report innaccurate results.
> 
> In hindsight, this change was unnecessarily abrupt. We’ve decided to roll back this change, instead providing the following warning before allowing such objects to fall back to the lm/glm tidier methods:
> 
>Tidiers for objects of class {subclass} are not maintained by the broom team, and are only supported through the {dispatched_method} tidier method. Please be cautious in interpreting and reporting broom output."
> 
> In addition,
> 
> Restores tidiers for summary.lm objects (#953 by @grantmcdermott)
> Deprecate tidiers for the lfe package, which was archived from CRAN.
> Various bug fixes and improvements to documentation and errors.

I can confirm that my functions now work again.

**Comment by IndrajeetPatil** [comment]
Maybe `parameters` can be of help here?

``` r
library(parameters)
library(dplyr)

mod <- summary(lm(formula = wt ~ am * cyl, data = mtcars))  

model_parameters(mod) %>%
  standardize_names(style = "broom") %>%
  tibble::as_tibble()
#> # A tibble: 4 x 9
#>   term       estimate std.error conf.level conf.low conf.high statistic df.error
#>   <chr>         <dbl>     <dbl>      <dbl>    <dbl>     <dbl>     <dbl>    <dbl>
#> 1 (Intercep…   1.66      0.587        0.95    0.455     2.86      2.82        28
#> 2 am          -0.956     0.793        0.95   -2.58      0.668    -1.21        28
#> 3 cyl          0.304     0.0826       0.95    0.135     0.473     3.68        28
#> 4 am:cyl       0.0328    0.130        0.95   -0.234     0.300     0.252       28
#> # … with 1 more variable: p.value <dbl>
```

<sup>Created on 2021-02-23 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>**

**Comment by harrelfe** [comment]
Please report this to `broom`, not here.
