### ISSUE TITLE
Error: "object 'nact' not found" when fitting logistic regression with only intercept using lrm

### ISSUE THREAD

**Issue by DInfanger** [harrelfe/rms#95]
When fitting a logistic regression model using `lrm` with only an intercept, the error `object 'nact' not found` is displayed. See the reproducible example below. I'm using R version 4.0.2 and `rms` version 6.0-1:

``` r

library(rms)

sessionInfo()$otherPkgs$rms$Version
#> [1] "6.0-1"

y <- rbinom(100, 1, 0.6)

mod <- lrm(y~1)
#> Error in lrm(y ~ 1): object 'nact' not found

# With data frame

dat <- data.frame(y = y)

mod <- lrm(y~1, data = dat)
#> Error in lrm(y ~ 1, data = dat): object 'nact' not found

# Changing na.action

mod <- lrm(y~1, na.action = na.omit)
#> Error in lrm(y ~ 1, na.action = na.omit): object 'nact' not found
mod <- lrm(y~1, na.action = na.exclude)
#> Error in lrm(y ~ 1, na.action = na.exclude): object 'nact' not found
```

<sup>Created on 2020-09-25 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by harrelfe** [comment]
`rms` does not allow intercept-only models.  You can get the -2 log likelihood for such models from the fit object for the full model.
