### ISSUE TITLE
Error in running nomogram()

### ISSUE THREAD

**Issue by xiw588** [harrelfe/rms#96]
Hi, I am trying to plot a nomogram for survival analysis but got the following error message. 

Error in value.chk(at, i, NA, -nint, Limval, type.range = "full") : 
  variable Age does not have limits defined by datadist

Can you please help me look into this?

Thank you.

**Comment by harrelfe** [comment]
Since you are keeping the code you used a secret there is no way I can help.  Please read guidelines about self-contained minimal working examples, etc.
