### ISSUE TITLE
how to calculate the 95% confidence interval of bootstraping c-index?

### ISSUE THREAD

**Issue by Wenlei77** [harrelfe/rms#98]
Hello, 

I have computerized a nomogram by using the nomogram() function from "rms" package.

Next, with the use of "validate()" function for resampling validation of the nomogram, I can obtain the c-index. Now I am wondering if there is a way to calculate the 95% confidence interval of bootstraping c-index?

Here are the codes for the calculation of bias corrected c-index:
v <- validate(fit, method = 'boot', B = 1000, dxy = T, bw = F)
Dxy = v[rownames(v)=="Dxy", colnames(v)=="index.corrected"]
bias_corrected_c_index  <- abs(Dxy)/2+0.5

Thanks a lot.

**Comment by harrelfe** [comment]
This is not available in `rms`.  We need someone to publish an article on how to do this, and I'll implement it.
